### PR TITLE
Provide preset for mutt.header_cache

### PR DESCRIPTION
**Pull request by nottwo**

### CODE REVIEW

**Comment by mwnx** [comment]
Is there a reason for sourcing $MUTTERER_SYSTEM_PRESETS/lib? Do you plan on
expanding the file?

**Comment by nottwo** [comment]
Sorry, I was getting a syntax error & I cargo-culted `$MUTTERER_SYSTEM_PRESETS/lib`.  I'm still learning how the all pieces fit together.

I've fixed the commit.  Thanks for pointing it out.

**Comment by mwnx** [comment]
I tried your preset out, and it does work.

I just realised why you want to put it in mutterer: because you're using a
per-user cache directory. After reading the doc, I just assumed you were
going to use one file for all users since that seemed like the simpler
solution.

I tried the single file solution after trying your preset, and as it turns
out they both seem to work just as well, and a single file just feels
cleaner to me. Note I only had one large (700MB) directory to test the
efficiency of both solutions on. Maybe results are different in the case of
several large directories but I doubt it.

The single-file configuration I used is:

    header_cache = ~/.mutt/header_cache

That being said, if you still want to provide a per folder solution, I would
ask that the cache directories (or files) not be stored in %folder, the
reason being that this interferes slightly with mutt's sidebar patch: the
*.cache directories get put in the sidebar when the mailboxes option is set
as below.

    mailboxes `find ~/.mail/ -maxdepth 2 -mindepth 1 -type d ! -regex ~/.mail/"\..*" -printf "+'%P' "`

Or supposing that you do store it in %folder, add a dot ('.') in front.
Otherwise, the .mutt/ directory seems like an appropriate place, considering
that these cache directories or files are mutt specific.

                                     *

Actually, I realise that this is a pretty specific config for "mailboxes"...
Might be interesting to add it to some presets/mutt-sensible-defaults file
among other things. What do you think? It should be useful for pretty much
everyone else using mutterer's default configs, shouldn't it?

-- 
mwnx
GPG: AEC9 554B 07BD F60D 75A3 AF6A 44E8 E4D4 0312 C726

**Comment by nottwo** [comment]
I don't use the sidebar patch & so didn't see the cache files polluting mutt.

I thought it made sense to keep the different accounts' caches separate.  If
one decides to remove an account, it wouldn't wipe out the header caches for
any remaining accounts.

Rather than putting it in %folder/%id.cache, maybe
~/.mutterer/configs/_%id/header.cache ?

**Comment by mwnx** [comment]
On Mon, Jul 13, 2015 at 01:19:37PM -0700, Trannie Carter wrote:
> I don't use the sidebar patch & so didn't see the cache files polluting mutt.
> 
> I thought it made sense to keep the different accounts' caches separate.  If
> one decides to remove an account, it wouldn't wipe out the header caches for
> any remaining accounts.
> 
> Rather than putting it in %folder/%id.cache, maybe
> ~/.mutterer/configs/_%id/header.cache ?

Well, there's no guarantee that these files −or indeed the whole
.mutterer/configs directory− won't be erased anytime mutterer is run since
the .mutterer/configs directory is just for storing generated configs.

One of

    %folder/.%id.header_cache
    ~/.mutt/%id.header_cache
    %folder/.header_cache/%id
    ~/.mutt/header_cache/%id

would be good. My preference is for the last two ;)

**Comment by nottwo** [comment]
@mwnx I updated the commit to use %folder/.header_cache/%id/

**Comment by mwnx** [comment]
Added a small correction. See last commit on experimental. Try it out to
make sure it works.

-mutt.header_cache              ?= \"%folder/.header_cache/%id/\"
+mutt.header_cache              ?= "\"%folder/.header_cache/%id/\""

**Pull request closed without merging**
