### PR TITLE
Configure folders when detecting Gmail

### PR DESCRIPTION
**Pull request by nottwo**

### CODE REVIEW

**Comment by mwnx** [comment]
I must say this isn't the way I use my gmail account; I just ignore the
"[Gmail]" folders. But I suppose most people would want to use the "[Gmail]"
folders as per your patch, so I'm making this the default behaviour and
adding a switching mechanism for weirdos like me.

I added these changes to the experimental branch. Can you check it out and
see if it works for you before I rebase it on master? You shouldn't need to
make any changes to your config.


Thanks for your interest in Mutterer! :)

**Comment by mwnx** [comment]
I'm also noticing that when I apply your (modified) patch, it appears on
github as originating from another user by the name of Trannie Carter
(username tcarter instead of nottwo). Not sure what to do about that...
sorry. I might try to fix it by doing a nasty amend, unless you have another
idea.

**Comment by nottwo** [comment]
Sorry, I misconfigured my git author info.  I've force-pushed a corrected
commit to my gmail-folders branch & will update the pull-request if necessary.

I'd recommend you grab the comit & force-push over your experimental branch to
fix it up since it's _experimental_ and hopefully no one is basing any of their
work on that branch, but I'll defer to your judgement there.

thanks!

**Comment by nottwo** [comment]
re: the switching mechanism you mentioned

Is this just overriding `mutt.spoolfile`, `mutt.record`, `mutt.postponed`,
`mutt.trash` in the `.muttererrc`?

I was surprised when the settings for those folders in `presets/defaults`
created directories in the filesystem called `[Ss][Ee][Nn][Tt]` if `Sent` (for
example) didn't already exist.

Seems like mutt will use the pattern to match an existing folder, but falls
back to the literal value if the directory does not exist.

Perhaps it would be possible to also specify a default value if the pattern
does not match.

**Comment by mwnx** [comment]
On Wed, Jul 08, 2015 at 12:41:13PM -0700, Trannie Carter wrote:
> Sorry, I misconfigured my git author info.  I've force-pushed a corrected
> commit to my gmail-folders branch & will update the pull-request if necessary.
> 
> I'd recommend you grab the comit & force-push over your experimental branch to
> fix it up since it's _experimental_ and hopefully no one is basing any of their
> work on that branch, but I'll defer to your judgement there.
> 
> thanks!

Force-push done on experimental.

Please tell me if the experimental branch still works for you.

**Comment by mwnx** [comment]
On Wed, Jul 08, 2015 at 12:51:12PM -0700, Trannie Carter wrote:
> re: the switching mechanism you mentioned
> 
> Is this just overriding `mutt.spoolfile`, `mutt.record`, `mutt.postponed`,
> `mutt.trash` in the `.muttererrc`?
> 
> I was surprised when the settings for those folders in `presets/defaults`
> created directories in the filesystem called `[Ss][Ee][Nn][Tt]` if `Sent` (for
> example) didn't already exist.
> 
> Seems like mutt will use the pattern to match an existing folder, but falls
> back to the literal value if the directory does not exist.
> 
> Perhaps it would be possible to also specify a default value if the pattern
> does not match.

Actually, this is a bug that I haven't really bothered fixing yet.
This is caused by the following in presets/defaults:

    mutt.spoolfile                 ?= %box/[Ii][Nn][Bb][Oo][Xx]
    mutt.record                    ?= %box/[Ss][Ee][Nn][Tt]
    mutt.postponed                 ?= %box/[Dd][Rr][Aa][Ff][Tt][Ss]
    mutt.trash                     ?= %box/[Tt][Rr][Aa][Ss][Hh]

The [...] patterns are evaluated by mutterer (well, by bash, from the
bash script mutterer generates, to be more precise).

A possible solution might be to do something like

    ... ?= $(if [[ -e %box/[Ii][Nn][Bb][Oo][Xx] ]]; then\
                 %box/[Ii][Nn][Bb][Oo][Xx]\
             else\
                 %box/Inbox\
             fi)

But the problem is if someone is just setting up mutterer and doesn't have
anything in his mail folder, this will create folders which probably won't
correspond to the remote folder.

So the user might end up with an INBOX folder as well as the Inbox folder
after launching offlineimap for the first time.

So yeah, not sure what the best solution is here. What I've done is just
manually create the missing folder when Mutt told me it didn't exist.

I guess a slight improvement would be to quote the [...]s, so that these
expressions are evaluated by Mutt rather than Mutterer. That would at least
have the advantage that the user doesn't have to redo a "mutterer install"
after manually creating the missing folders.

Now I'm rambling... I'll see what can be done later. And if you have any
suggestions of course, go ahead.

**Comment by mwnx** [comment]
> I guess a slight improvement would be to quote the [...]s, so that these
> expressions are evaluated by Mutt rather than Mutterer. That would at least
> have the advantage that the user doesn't have to redo a "mutterer install"
> after manually creating the missing folders.

Actually, redoing a "mutterer install" is not necessary in this case now
that I think about it. Indeed, since [Ii][Nn][Bb][Oo][Xx] is left as-is by
bash when it doesn't find a matching file, this pattern would be recorded
verbatim in the generated Mutt config and therefore Mutt would be able to
find the newly created folder after all.

So I really have no improvement to propose over the current situation for
now.

Well... I guess the "mutterer imap" command could create any missing folders
after invoking offlineimap. But this isn't a perfect solution either. It
supposes the user will use the "mutterer imap" command for a start, and
quite frankly even I never bother invoking offlineimap indirectly like that.

Maybe prompting the user to do an initial offlineimap sync when an account
is added, and then adding the missing folders... that sounds about right.

**Comment by mwnx** [comment]
On Wed, Jul 08, 2015 at 12:51:12PM -0700, Trannie Carter wrote:
> Perhaps it would be possible to also specify a default value if the pattern
> does not match.

Okay, I'm an idiot.

Yes!

The following (which is exactly what I wrote previously) should
actually work just fine:

    ... ?= $(if [[ -e %box/[Ii][Nn][Bb][Oo][Xx] ]]; then\
                 %box/[Ii][Nn][Bb][Oo][Xx]\
             else\
                 %box/Inbox\
             fi)

That way, Mutt will prompt the user to create %box/Inbox instead of
%box/[Ii][Nn][Bb][Oo][Xx]. (I was thinking about having the mutterer script
mkdir the directory before and ended up writing the sensible solution
instead by mistake without even realising it :])

I'll work on that a bit later then. Thanks for the input :) And sorry for
all the wasted text.

**Comment by nottwo** [comment]
I like the `if then else` approach as it tries to capture common existing
setups, but falls back to sensible defaults.

Many users will probably already have values they would like to use for those
folders.

If they don't have a preference, folder names like `Inbox` are much better than
`[Ii][Nn][Bb][Oo][Xx]`.

**Comment by nottwo** [comment]
Your experimental branch is working fine in my setup, thanks!

**Comment by mwnx** [comment]
Added default folder names support in experimental.

**Pull request closed without merging**
