### PR TITLE
Goto internal subdir

### PR DESCRIPTION
**Pull request by nottwo**
Now that I have mutt.record pointing to `[GMail].Sent Mail` and have tried
to use the `_s` macro, I've discovered that mutt's interactive
&lt;change-folder&gt; behavior doesn't play nice with a macro playback that
contains spaces.

Normally when you interactively change folders, mutt responds immediately
to a space character.  It seems to reset the path specification.

I haven't found a way to escape an embedded space in a folder path.

In this case, the built-in shortname `<` for `$record` gets past the issue.

I didn't find any suitable shortnames for the other folder names.

I threw in `!` for `$spoolfile` for good measure.

I suspect a `%folder` that has a space in its path will also break the
goto_subdir macros...

### CODE REVIEW

**Comment by mwnx** [comment]
Thanks for pointing this problem out. I found this link on the mutt mailing
list relating to this exact problem:

    http://comments.gmane.org/gmane.mail.mutt.devel/19515

It turns out spaces need to be escaped with <quote-char> (^V (CTRL-V) by
default). It should be easy to escape spaces with "<quote-char>" in the
mutterer config. I'll add that to my TODO list for tomorrow :)

I hope you don't mind if I don't apply your patch as a result.

**Comment by nottwo** [comment]
I figured mutt must have a way to quote the space.

No problem closing this PR

**Comment by mwnx** [comment]
Bug fixed in experimental. Please check it out and let me know if all works
well for you.

**Comment by nottwo** [comment]
The version in your experimental left mutt waiting for input while changing directories.

The quote-char had been inserted, allowing me to complete the path with " Mail<return>".

Replacing the literal ' ' character with <space> fixes the issue.

PR shortly.

**Pull request closed without merging**
